# Generated by Django 5.0 on 2024-05-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalPerformance',
        ),
    ]
